import * as Yup from 'yup';

import { REQUIRED_STRING_VALIDATION } from '~constants/validations';

import { USER_FIELDS_NAMES } from './constants';

export const VALIDATION_SCHEMA = Yup.object().shape({
  [USER_FIELDS_NAMES.DATE_OF_BIRTH]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.EMAIL]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.ID_NUMBER]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.ID_TYPE]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.LASTNAME]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.NAME]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.NOTIFICATION_METHOD]: REQUIRED_STRING_VALIDATION,
  [USER_FIELDS_NAMES.PHONE]: REQUIRED_STRING_VALIDATION
});
